name: "Submit to Web Store"
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Clone Another Repository
        run: |
          git clone https://github.com/AtomMaterialUI/iconGenerator

      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.x

      - uses: oven-sh/setup-bun@v2
        name: Setup Bun

      - name: Install
        run: bun install

      - name: Build chrome artifact
        run: bun run build -- --zip

      - name: Build firefox artifact
        run: bun run build -- --zip --target=firefox-mv3

#      - name: Create Release
#        uses: softprops/action-gh-release@v1
#        with:
#          generate_release_notes: true
#          body: |
#            ## Changelog
#            Please see the [changelog](https://github.com/microvoid/notion-ai-anywhere/blob/main/CHANGELOG.md)
#          files: |
#            build/chrome-mv3-prod.zip
#            build/firefox-mv3-prod.zip
#            build/edge-mv3-prod.zip

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
          firefox-file: build/firefox-mv3-prod.zip
          edge-file: build/edge-mv3-prod.zip
          verbose: true
