name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 22.x

      - uses: oven-sh/setup-bun@v2
        name: Setup Bun

      - name: Install
        run: bun install

#      - uses: pnpm/action-setup@v2.2.2
#        with:
#          version: 7.11.0
#          run_install: true

      - name: Build and zip extension artifact
        run: bun run build -- --zip

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
