name: "Publish to Chrome Web Store"
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Clone Another Repository
        run: |
          git clone https://github.com/AtomMaterialUI/iconGenerator

      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.x

      - uses: oven-sh/setup-bun@v2
        name: Setup Bun

      - name: Install
        run: bun install

      - name: Build chrome artifact
        run: bun run build -- --zip

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
          verbose: true
